#!/bin/bash

is_sourced() {
  [ "$0" != "$BASH_SOURCE" ]
}

packages() {
  if [ -n "${CRATER_PACKAGES:-}" ]; then
    echo "$CRATER_PACKAGES"
    return 0
  fi

  read -r -d '' CRATER_PACKAGES << "PACKAGES"
lua-5.1.5 b3882111ad02ecc6b972f8c1241647905cb2e3fc https://www.lua.org/ftp/lua-5.1.5.tar.gz
lua-5.2.4 ef15259421197e3d85b7d6e4871b8c26fd82c1cf https://www.lua.org/ftp/lua-5.2.4.tar.gz
lua-5.3.4 79790cfd40e09ba796b01a571d4d63b52b1cd950 https://www.lua.org/ftp/lua-5.3.4.tar.gz
luajit-2.0.4 6e533675180300e85d12c4bbeea2d0e41ad21172 https://luajit.org/download/LuaJIT-2.0.4.tar.gz
luajit-2.0.5 10427215da7d424fd9e48adbea087966053cdb6f https://luajit.org/download/LuaJIT-2.0.5.tar.gz
luajit-2.0.5+git 817932cb7910f5c3aad1220376b5ccec293020ad https://github.com/LuaJIT/LuaJIT/archive/046129dbdda5261c1b17469a2895a113d14c070a.tar.gz
luajit-2.1.0-beta2 59f5e037f9dfa2db21df42fc483cce63b5798f51 https://luajit.org/download/LuaJIT-2.1.0-beta2.tar.gz
luajit-2.1.0-beta3 e945cee354484db45576c3760a5cfd70e7a314bf https://luajit.org/download/LuaJIT-2.1.0-beta3.tar.gz
luarocks-2.2.2 eb867374e5a11edb705fd9fab3b47b083a9e55a6 https://luarocks.org/releases/luarocks-2.2.2.tar.gz
luarocks-2.3.0 5f1e1658ef8c7c9710fbc751cad79eb69ae2a891 https://luarocks.org/releases/luarocks-2.3.0.tar.gz
luarocks-2.4.2 3e595956eab7192036a4993c24125284cd789894 https://luarocks.org/releases/luarocks-2.4.2.tar.gz
luarocks-2.4.4 cb7f93e80d704b5f7ed93406ec6c950a2c969600 https://luarocks.org/releases/luarocks-2.4.4.tar.gz
PACKAGES
  echo "$CRATER_PACKAGES"
}

package_versions(){
  (set -o pipefail; packages | cut -d ' ' -f1)
  return $?
}

package() {
  local _version; _version="$1";
  (set -o pipefail; packages | grep -- "^$_version ")
  return $?
}

package_sha1sum() {
  local _version; _version="$1";
  (set -o pipefail;  package "$_version" | cut -d ' ' -f2)
  return $?
}

package_url() {
  local _version; _version="$1";
  (set -o pipefail; package "$_version" | cut -d ' ' -f3)
  return $?
}

check_prereqs() {
  if ! command -v 'cc'; then
    echo "'cc' (C compiler) not installed, required to build lua." 1>&2
    return 1
  fi

  if ! command -v 'unzip'; then
    echo "'unzip' not installed, required by luarocks." 1>&2
    return 1
  fi
}

download() {
  local _curl; _curl="$(command -v curl)";
  if [ "x$_curl" != "x" ]; then
    "$_curl" -LfsS "$1" --output "$2"
    return $?
  fi

  local _wget; _wget="$(command -v wget)";
  if [ "x$_wget" != "x" ]; then
    "$_wget" --max-redirect 1 --quiet "$1" --output-document "$2"
    return $?
  fi

  return 1
}

sha1() {
  local _sha1_file; _sha1_file="$1"; shift

  (set -o pipefail; sha1sum -b "$_sha1_file" 2> /dev/null | cut -d ' ' -f1)
}

sha1_check() {
  local _file_path; _file_path="$1"; shift
  local _file_sha1; _file_sha1="$1"; shift

  [ -f "$_file_path" -a "x$_file_sha1" != "x" ] &&
    [ "$(sha1 "$_file_path")" == "$_file_sha1" ]
}

download_sha1() {
  local _url; _url="$1"; shift
  local _file; _file="$1"; shift
  local _sha1; _sha1="$1"; shift

  if [ -f "$_file" ] && sha1_check "$_file" "$_sha1"; then
    return 0;
  fi

  download "$_url" "$_file" && sha1_check "$_file" "$_sha1"
}

extract_tgz() {
  local _tgz_url; _tgz_url="$1"; shift
  local _tgz_sha1; _tgz_sha1="$1"; shift

  local _tgz_basename; _tgz_basename="$(basename "$_tgz_url")" 
  local _tgz_cache; _tgz_cache="$crater_cache_dir/$_tgz_basename"
  local _tgz_dir_basename; _tgz_dir_basename="${_tgz_basename%.tar.gz}"

  local _tmp_dir;
  
  download_sha1 "$_tgz_url" "$_tgz_cache" "$_tgz_sha1" &&
    _tmp_dir="$(mktemp -d --tmpdir="$crater_tmp_dir" "$_tgz_basename.XXXX")" &&
    tar -xzf "$_tgz_cache" -C "$_tmp_dir" &&
    echo "$_tmp_dir/"*
}

mark_installed() {
  local _name;
  for _name in $@; do
    touch "$CRATER_CURRENT/.installed_$_name" || return $?
  done
}

check_installed() {
  local _name;
  for _name in $@; do
    if [ ! -f "$CRATER_CURRENT/.installed_$_name" ]; then
      return 1;
    fi
  done
}

check_compile() {
   local _src; _src="$1"; shift

   echo "$_src" | 
     if [ $# -gt 0 ]; then
       cc -o /dev/null -x c - "$@" 2> /dev/null;
     else
       cc -o /dev/null -x c - 2> /dev/null;
     fi
}

check_library() {
  local _library; _library="$1"; shift
  check_compile "int main(){}" "-l$_library"
}

install_lua() {
  local _lua_tgz_url; _lua_tgz_url="$1"; shift
  local _lua_tgz_sha1; _lua_tgz_sha1="$1"; shift

  local _install_prefix; _install_prefix="$CRATER_CURRENT";
  mkdir -p "$CRATER_CURRENT" || return $? 
  (
    local _lua_src;
    _lua_src="$(extract_tgz "$_lua_tgz_url" "$_lua_tgz_sha1")" || return $?

    cd "$_lua_src"
    local MAKEOPTS;
    if grep -q LuaJIT Makefile; then

      MAKEOPTS="PREFIX='$_install_prefix' INSTALL_INC='$_install_prefix/include'"
      make -j8 $MAKEOPTS &&
        make $MAKEOPTS install &&
        if [ ! -e "$_install_prefix/bin/lua" ]; then
          (
            cd "$_install_prefix/bin"
            # symlink to luajit
            for f in luajit*; do
              if [ -f "$f" ]; then
                ln -s "$f" lua
                break
              fi
            done
          )
        fi
        if [ ! -e "$_install_prefix/lib/liblua.a" ]; then
          (
            cd "$_install_prefix/lib"
            for f in libluajit*.a; do
              if [ -f "$f" ]; then
                ln -s "$f" liblua.a
                break
              fi
            done
          )
        fi

        if [ ! -d "$_install_prefix/man" -a -d "$_install_prefix/share/man" ]; then
          (
            cd "$_install_prefix"
            ln -s share/man man
          )
        fi
    else

      (rm src/luaconf.h; sed 's/#define LUA_ROOT[ \t].*/#define LUA_ROOT\t"'"$(echo "${_install_prefix}/" | sed 's/\//\\\//g')"'"/g' > src/luaconf.h) < src/luaconf.h
      if ! check_library 'readline'; then
        # disable readline support
        sed -i'' '/LUA_USE_READLINE/d' src/luaconf.h
        sed -i'' 's/-lreadline//g' src/Makefile
      fi
      if ! check_library 'ncurses'; then
        # disable ncurses support (lua-5.2.x?)
        sed -i'' 's/-lncurses//g' src/Makefile
      fi

      MAKEOPTS="INSTALL_TOP='$_install_prefix'"
      local _luapc="$_install_prefix/lib/pkgconfig/lua.pc"
      make -j8 $MAKEOPTS linux &&
        make $MAKEOPTS linux install &&
        mkdir -p "$_install_prefix/lib/pkgconfig" &&
        (make $MAKEOPTS pc > "$_luapc"  || rm -v "$_luapc")

    fi

    if [ ! -e "$_install_prefix/bin/lua" ]; then
      echo 'lua binary not found' 1>&2
      exit 1
    fi

    if [ ! -e "$_install_prefix/lib/liblua.a" ]; then
      echo 'liblua.a not found' 1>&2
      exit 1
    fi

    cd ../ && rm -rvf "$_lua_src"
  ) 2>&1 | tee "$CRATER_CURRENT/.log_install_lua"
  return ${PIPESTATUS[0]};
}

install_luarocks() {
  local _luarocks_tgz_url; _luarocks_tgz_url="$1"; shift
  local _luarocks_tgz_sha1; _luarocks_tgz_sha1="$1"; shift

  local _install_prefix; _install_prefix="$CRATER_CURRENT";
  (
    local _luarocks_src;
    _luarocks_src="$(extract_tgz "$_luarocks_tgz_url" "$_luarocks_tgz_sha1")" &&
      cd "$_luarocks_src" &&
      ./configure --prefix="$_install_prefix" --sysconfdir="$_install_prefix" --with-lua="$_install_prefix" --force-config &&
      make &&
      make install &&
      cd ../ && rm -rvf "$_luarocks_src"
  ) 2>&1 | tee "$CRATER_CURRENT/.log_install_luarocks"
  return ${PIPESTATUS[0]};
}

if [ "$CRATER_SOURCE_ONLY" == "1" ] && is_sourced; then
  return
fi

: ${CRATER_ROOT:="$(dirname "$BASH_SOURCE")/.crater"}
# require that CRATER_ROOT be a dot-dir prefixed with '.crater'.
# since crater will be "rm -rf"-ing things beneath this dir, and
# generally treating it as its own space, we need to make sure
# it's not something like '/' or '/home/foo' or '/usr'.
CRATER_ROOT="$(readlink -f "$CRATER_ROOT")"
if [[ "$?" -ne "0" || "$(basename "$CRATER_ROOT")" != ".crater"* ]]; then
  if is_sourced; then
    return 1;
  else
    exit 1;
  fi
fi

if [ -d "$CRATER_ROOT/current" -a \( -z "$CRATER_LUA" -o -z "$CRATER_LUAROCKS" \) ]; then
  CRATER_CURRENT="$(readlink -e "$CRATER_ROOT/current")"
  if [ -z "$CRATER_LUAROCKS" ]; then
    CRATER_LUAROCKS=$(basename "$CRATER_CURRENT")
  fi
  if [ -z "$CRATER_LUA" ]; then
    CRATER_LUA="$(basename "$(dirname "$CRATER_CURRENT")")"
  fi
else
  : ${CRATER_LUA:="lua-5.3.4"}
  : ${CRATER_LUAROCKS:="luarocks-2.4.2"}
fi
CRATER_CURRENT="$CRATER_ROOT/${CRATER_LUA}/${CRATER_LUAROCKS}"

if ! check_installed 'all' && ! (
  crater_tmp_dir="$CRATER_ROOT/tmp"
  crater_cache_dir="$CRATER_ROOT/cache"

  mkdir -p "$crater_tmp_dir" "$crater_cache_dir" "$CRATER_CURRENT"

  exec &> "$CRATER_ROOT"/lastlog

  set -x; export SHELLOPTS;

  lua_tgz_url="$(package_url "$CRATER_LUA")" &&
    lua_tgz_sha1="$(package_sha1sum "$CRATER_LUA")" &&
    luarocks_tgz_url="$(package_url "$CRATER_LUAROCKS")" &&
    luarocks_tgz_sha1="$(package_sha1sum "$CRATER_LUAROCKS")" ||
    if is_sourced; then
      return 1
    else
      exit 1
    fi

  rm -rf "$CRATER_CURRENT"
  check_prereqs &&
    install_lua "$lua_tgz_url" "$lua_tgz_sha1" &&
    install_luarocks "$luarocks_tgz_url" "$luarocks_tgz_sha1" &&
    mark_installed "$lua_tgz_sha1" "$luarocks_tgz_sha1" 'all' &&
    rm -rf "$crater_tmp_dir"/{*,.[!.]*,..?*} || exit $?
) then
  if is_sourced; then
    return $install_result
  else
    exit $install_result
  fi
fi

if [ "$(readlink -f "$CRATER_ROOT/current")" != "$CRATER_CURRENT" ]; then
  ln -nfs "$CRATER_CURRENT" "$CRATER_ROOT/current"
fi
export CRATER_CURRENT

export CRATER_PATH_PREFIX="$CRATER_CURRENT/bin"
if [ -z "$CRATER_PATH_ORIGINAL" ]; then
  export CRATER_PATH_ORIGINAL="$PATH"
fi
export PATH="$CRATER_PATH_PREFIX:$CRATER_PATH_ORIGINAL"

export CRATER_MANPATH_PREFIX="$CRATER_CURRENT/man"
if [ -z "$CRATER_MANPATH_ORIGINAL" ]; then
  export CRATER_MANPATH_ORIGINAL="$MANPATH"
fi
export MANPATH="$CRATER_MANPATH_PREFIX:$CRATER_MANPATH_ORIGINAL"

export CRATER_PKG_CONFIG_PATH_PREFIX="$CRATER_CURRENT/lib/pkgconfig"
if [ -z "$CRATER_PKG_CONFIG_PATH_ORIGINAL" ]; then
  export CRATER_PKG_CONFIG_PATH_ORIGINAL="$PKG_CONFIG_PATH"
fi
export PKG_CONFIG_PATH="$CRATER_PKG_CONFIG_PATH_PREFIX:$CRATER_PKG_CONFIG_PATH_ORIGINAL"

if [ $# -gt 0 ]; then
  exec "$@"
fi

